# Generated by Django 4.2.8 on 2023-12-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrecord',
            name='date',
        ),
    ]
